{
  "openapi": "3.0.0",
  "info": {
    "title": "Package",
    "version": "v1",
    "description": "Disponibiliza serviços para atuar sobre um pacote."
  },
  "servers": [
    {
      "url": "https://stg.api.loggi.com"
    },
    {
      "url": "https://api.loggi.com"
    }
  ],
  "paths": {
    "/oauth2/token": {
      "post": {
        "summary": "Criar/Atualizar Token",
        "description": "Solicitação e atualização de token. O campo **idToken** deve ser informado no **Header** _Authorization_ de cada requisição à API.",
        "operationId": "requestOAuthToken",
        "responses": {
          "200": {
            "description": "Criação ou atualização de token com sucesso.",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "idToken": {
                      "type": "string",
                      "description": "Token de autenticação. Deve ser informado no campo Auhtorization de cada endpoint da API.",
                      "example": "eyJraWQiOiJIWTlqQk43Y2pJajYzN2RobUZ6"
                    },
                    "expiresIn": {
                      "type": "string",
                      "description": "Tempo de expiração do token em segundos.",
                      "example": "300"
                    }
                  },
                  "description": "Objeto que representa os dados de autenticação OAuth2"
                }
              }
            }
          },
          "400": {
            "description": "Mensagem do cliente não segue a especificação.",
            "content": {
              "application/json": {
                "examples": {
                  "invalid_argument": {
                    "value": {
                      "code": 3,
                      "message": "Mensagem do cliente não segue a especificação",
                      "details": []
                    }
                  },
                  "failed_preconditions": {
                    "value": {
                      "code": 9,
                      "message": "Request with invalid data",
                      "details": [
                        {
                          "@type": "type.googleapis.com/google.rpc.BadRequest",
                          "fieldViolations": [
                            {
                              "field": "loggi_key",
                              "description": "invalid format"
                            }
                          ]
                        }
                      ]
                    }
                  }
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Falha de autenticação.",
            "content": {
              "application/json": {
                "example": {
                  "code": 16,
                  "message": "Falha de autenticação",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Sem autorização para acessar o serviço.",
            "content": {
              "application/json": {
                "example": {
                  "code": 7,
                  "message": "Falha de autenticação",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "429": {
            "description": "Requisições massivas bloqueadas.",
            "content": {
              "application/json": {
                "example": {
                  "code": 8,
                  "message": "Requisições massivas bloqueadas",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno",
            "content": {
              "application/json": {
                "example": {
                  "code": 13,
                  "message": "Erro interno",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Serviço temporariamente indisponível.",
            "content": {
              "application/json": {
                "example": {
                  "code": 14,
                  "message": "Serviço temporariamente indisponível",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "required": [
                  "client_id",
                  "client_secret"
                ],
                "properties": {
                  "client_id": {
                    "type": "string",
                    "description": "Id do cliente cadastrado na Loggi.",
                    "example": "loggi_cliente_xpto"
                  },
                  "client_secret": {
                    "type": "string",
                    "description": "Chave secreta gerada pela Loggi.",
                    "example": "PaSsWoRd!St@ong&R"
                  }
                },
                "description": "Objeto que representa os parâmetros para obtenção de um Token de acesso."
              }
            }
          }
        },
        "tags": [
          "OAuth2Token"
        ]
      }
    },
    "/v1/companies/{company_id}/packages": {
      "patch": {
        "summary": "Atualizar dados de um pacote",
        "description": "",
        "operationId": "PackageUpdate",
        "security": [
          {
            "OAuth2": []
          }
        ],
        "responses": {
          "200": {
            "description": "",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                }
              }
            }
          },
          "400": {
            "description": "Mensagem do cliente não segue a especificação",
            "content": {
              "application/json": {
                "example": {
                  "code": 3,
                  "message": "Mensagem do cliente não segue a especificação",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Falha de autenticação",
            "content": {
              "application/json": {
                "example": {
                  "code": 16,
                  "message": "Falha de autenticação",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Sem autorização para acessar o serviço",
            "content": {
              "application/json": {
                "example": {
                  "code": 7,
                  "message": "Falha de autenticação",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "code": 5,
                  "message": "Recurso não encontrado",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "429": {
            "description": "Requisições massivas bloqueadas",
            "content": {
              "application/json": {
                "example": {
                  "code": 8,
                  "message": "Requisições massivas bloqueadas",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno",
            "content": {
              "application/json": {
                "example": {
                  "code": 13,
                  "message": "Erro interno",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Serviço temporariamente indisponível",
            "content": {
              "application/json": {
                "example": {
                  "code": 14,
                  "message": "Serviço temporariamente indisponível",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "examples": {
                "Atualizar pacote com destinatário e endereço no formato CorreiosAddress": {
                  "value": {
                    "package": {
                      "shipTo": {
                        "name": "Maria das Dores",
                        "email": "email@email.com",
                        "phoneNumber": "11998765432",
                        "federalTaxId": "12345678911",
                        "address": {
                          "correios": {
                            "logradouro": "Alameda Santos",
                            "numero": "2400",
                            "complemento": "10 andar",
                            "bairro": "Jardim Paulista",
                            "cep": "1419100",
                            "cidade": "São Paulo",
                            "uf": "SP"
                          }
                        }
                      },
                      "updateMask": "shipTo"
                    }
                  }
                },
                "Atualizar pacote com destinatário e endereço no formato LineAddress": {
                  "value": {
                    "package": {
                      "shipTo": {
                        "name": "Maria das Dores",
                        "email": "email@email.com",
                        "phoneNumber": "11998765432",
                        "federalTaxId": "12345678911",
                        "address": {
                          "lines": {
                            "addressLine1": "Alameda Santos, 2400",
                            "addressLine2": "10 andar",
                            "postalCode": "1419100",
                            "city": "São Paulo",
                            "state": "SP"
                          },
                          "country": "Brasil"
                        }
                      },
                      "updateMask": "shipTo"
                    }
                  }
                },
                "Atualizar pacote com destinatário": {
                  "value": {
                    "package": {
                      "shipTo": {
                        "name": "Maria das Dores",
                        "email": "email@email.com",
                        "phoneNumber": "11998765432",
                        "federalTaxId": "12345678911"
                      },
                      "updateMask": "shipTo.name,shipTo.email,shipTo.phoneNumber,shipTo.federalTaxId"
                    }
                  }
                },
                "Atualizar pacote com endereço no formato CorreiosAddress": {
                  "value": {
                    "package": {
                      "shipTo": {
                        "address": {
                          "correios": {
                            "logradouro": "Alameda Santos",
                            "numero": "2400",
                            "complemento": "10 andar",
                            "bairro": "Jardim Paulista",
                            "cep": "1419100",
                            "cidade": "São Paulo",
                            "uf": "SP"
                          }
                        }
                      },
                      "updateMask": "shipTo.address"
                    }
                  }
                },
                "Atualizar pacote com endereço no formato LineAddress": {
                  "value": {
                    "package": {
                      "shipTo": {
                        "address": {
                          "lines": {
                            "addressLine1": "Alameda Santos, 2400",
                            "addressLine2": "10 andar",
                            "postalCode": "1419100",
                            "city": "São Paulo",
                            "state": "SP",
                            "country": "Brasil"
                          }
                        }
                      },
                      "updateMask": "shipTo.address"
                    }
                  }
                }
              },
              "schema": {
                "type": "object",
                "properties": {
                  "package": {
                    "type": "object",
                    "properties": {
                      "updateMask": {
                        "type": "string",
                        "description": "Identifica o campo do pacote que será atualizado.",
                        "example": "shipTo"
                      },
                      "shipTo": {
                        "type": "object",
                        "properties": {
                          "name": {
                            "type": "string",
                            "description": "Nome da pessoa destinatária associada ao pacote.",
                            "example": "Maria das Dores"
                          },
                          "email": {
                            "type": "string",
                            "description": "Email da pessoa destinatária associada ao pacote.",
                            "example": "email@email.com"
                          },
                          "phoneNumber": {
                            "type": "string",
                            "description": "Número de telefone da pessoa destinatária associada ao pacote.",
                            "example": 11998765432
                          },
                          "federalTaxId": {
                            "type": "string",
                            "description": "Número de identificação fiscal da pessoa destinatária associada ao pacote. Poder ser o número do CPF ou CNPJ.",
                            "example": 12345678911
                          },
                          "address": {
                            "oneOf": [
                              {
                                "type": "object",
                                "properties": {
                                  "correios": {
                                    "type": "object",
                                    "properties": {
                                      "logradouro": {
                                        "type": "string",
                                        "description": "Nome do endereço associado a pessoa destinatária do pacote.",
                                        "example": "Alameda Santos"
                                      },
                                      "numero": {
                                        "type": "string",
                                        "description": "Número que identifica o local onde o pacote será entregue para a pessoa destinatária associada ao pacote.",
                                        "example": 2400
                                      },
                                      "complemento": {
                                        "type": "string",
                                        "description": "Informações complementares associadas ao endereço da pessoa destinatária do pacote.",
                                        "example": "Apto 103, Bloco C"
                                      },
                                      "bairro": {
                                        "type": "string",
                                        "description": "Bairro do endereço associado a pessoa destinatária do pacote.",
                                        "example": "Centro"
                                      },
                                      "cep": {
                                        "type": "string",
                                        "description": "Código postal do endereço associado a pessoa destinatária do pacote.",
                                        "example": 12345000
                                      },
                                      "cidade": {
                                        "type": "string",
                                        "description": "Cidade do endereço associado a pessoa destinatária do pacote.",
                                        "example": "São Paulo"
                                      },
                                      "uf": {
                                        "type": "string",
                                        "description": "Unidade federativa do endereço associado a pessoa destinatária do pacote.",
                                        "example": "SP"
                                      }
                                    }
                                  }
                                },
                                "description": "Objeto que contém informações detalhadas do endereço compatível com o formato da API dos Correios."
                              },
                              {
                                "type": "object",
                                "properties": {
                                  "lines": {
                                    "type": "object",
                                    "properties": {
                                      "addressLine1": {
                                        "type": "string",
                                        "description": "Representação mais simples do endereço associado a pessoa destinatária do pacote. Comumente associado ao formato inserido pelo usuário.",
                                        "example": "Alameda Santos, 2400"
                                      },
                                      "addressLine2": {
                                        "type": "string",
                                        "description": "Informações complementares associadas ao endereço da pessoa destinatária do pacote.",
                                        "example": "Apto 103 - Bloco C"
                                      },
                                      "postalCode": {
                                        "type": "string",
                                        "description": "Código postal do endereço associado a pessoa destinatária do pacote. No Brasil, usa-se o CEP.",
                                        "example": 12345000
                                      },
                                      "city": {
                                        "type": "string",
                                        "description": "Cidade do endereço associado a pessoa destinatária do pacote.",
                                        "example": "São Paulo"
                                      },
                                      "state": {
                                        "type": "string",
                                        "description": "Unidade federativa do endereço associado a pessoa destinatária do pacote.",
                                        "example": "SP"
                                      },
                                      "country": {
                                        "type": "string",
                                        "description": "País do endereço associado a pessoa destinatária do pacote.",
                                        "example": "Brasil"
                                      }
                                    }
                                  }
                                },
                                "description": "Objeto que representa um endereço com padrão internacional."
                              }
                            ],
                            "description": "Objeto que representa um endereço nacional em formato dos Correios ou um endereço internacional. Ambas as representações são mutuamente exclusivas, sendo assim, só é possível utilizar uma delas por request."
                          }
                        },
                        "description": "Objeto que configura o formato da requisição de atualização do destinatário. Contém as informações da pessoa destinatária e do endereço de entrega."
                      }
                    }
                  }
                },
                "description": "Objeto que configura o formato da requisição de atualização de um pacote. Contém as informações a serem atualizadas."
              }
            }
          },
          "required": true
        },
        "parameters": [
          {
            "name": "company_id",
            "in": "path",
            "required": true,
            "description": "Código numérico fornecido pela Loggi para identificação.",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "loggi_key",
            "in": "query",
            "required": false,
            "description": "Código único gerado pela Loggi, ou seja, cada pacote deve ter um loggi_key único.",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tracking_code",
            "in": "query",
            "required": false,
            "description": "Código de rastreio do pacote, que é gerado pela Loggi ou pelo parceiro por meio da API de envio.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "tags": [
          "PackageUpdateAPI"
        ]
      }
    },
    "/v1/companies/{company_id}/packages/cancel": {
      "post": {
        "summary": "Cancelar envio",
        "description": "",
        "operationId": "PackageCancel",
        "security": [
          {
            "OAuth2": []
          }
        ],
        "responses": {
          "200": {
            "description": "Pacote cancelado com sucesso",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "warning_type": {
                      "type": "string",
                      "description": "Mensagem com a constante que identifica casos em que o cancelamento não pode ser confirmado.",
                      "example": "REDISPATCH_CANCELLATION"
                    },
                    "warning_message": {
                      "type": "string",
                      "description": "Mensagem de alerta para casos em que o cancelamento não pode ser confirmado.",
                      "example": "O pacote está com os correios. Vamos tentar cancelar e devolver pra você."
                    }
                  },
                  "description": "Objeto que configura a resposta da API de cancelamento de pacotes."
                }
              }
            }
          },
          "400": {
            "description": "Mensagem do cliente não segue a especificação",
            "content": {
              "application/json": {
                "example": {
                  "code": 3,
                  "message": "Mensagem do cliente não segue a especificação",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Falha de autenticação",
            "content": {
              "application/json": {
                "example": {
                  "code": 16,
                  "message": "Falha de autenticação",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "403": {
            "description": "Sem autorização para acessar o serviço",
            "content": {
              "application/json": {
                "example": {
                  "code": 7,
                  "message": "Acesso não autorizado",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "404": {
            "description": "Recurso não encontrado",
            "content": {
              "application/json": {
                "example": {
                  "code": 5,
                  "message": "Recurso não encontrado",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "429": {
            "description": "Requisições massivas bloqueadas",
            "content": {
              "application/json": {
                "example": {
                  "code": 8,
                  "message": "Requisições massivas bloqueadas",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "500": {
            "description": "Erro interno",
            "content": {
              "application/json": {
                "example": {
                  "code": 13,
                  "message": "Erro interno",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          },
          "503": {
            "description": "Serviço temporariamente indisponível",
            "content": {
              "application/json": {
                "example": {
                  "code": 14,
                  "message": "Serviço temporariamente indisponível",
                  "details": []
                },
                "schema": {
                  "type": "object",
                  "properties": {
                    "code": {
                      "type": "integer",
                      "format": "int32",
                      "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
                      "example": 14
                    },
                    "message": {
                      "type": "string",
                      "description": "Texto pequeno informativo sobre a falha.",
                      "example": "Requisição com credenciais inválidas."
                    },
                    "details": {
                      "type": "array",
                      "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
                      "items": {},
                      "example": []
                    }
                  }
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "company_id",
            "in": "path",
            "required": true,
            "description": "Código numérico fornecido pela Loggi para identificação.",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "loggi_key",
            "in": "query",
            "required": false,
            "description": "Código único gerado pela Loggi, ou seja, cada pacote deve ter um loggi_key único.",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "tracking_code",
            "in": "query",
            "required": false,
            "description": "Código de rastreio do pacote, que é gerado pela Loggi ou pelo parceiro por meio da API de envio.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "tags": [
          "PackageCancelAPI"
        ]
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2": {
        "type": "oauth2",
        "description": "Autenticação OAuth 2.0 para clientes da API.",
        "flows": {
          "clientCredentials": {
            "tokenUrl": "https://api.loggi.com/oauth2/token",
            "scopes": {}
          }
        }
      }
    },
    "schemas": {
      "v1PackageUpdateResponse": {
        "type": "object"
      },
      "v1PackageUpdateRequest": {
        "type": "object",
        "properties": {
          "package": {
            "type": "object",
            "properties": {
              "updateMask": {
                "type": "string",
                "description": "Identifica o campo do pacote que será atualizado.",
                "example": "shipTo"
              },
              "shipTo": {
                "type": "object",
                "properties": {
                  "name": {
                    "type": "string",
                    "description": "Nome da pessoa destinatária associada ao pacote.",
                    "example": "Maria das Dores"
                  },
                  "email": {
                    "type": "string",
                    "description": "Email da pessoa destinatária associada ao pacote.",
                    "example": "email@email.com"
                  },
                  "phoneNumber": {
                    "type": "string",
                    "description": "Número de telefone da pessoa destinatária associada ao pacote.",
                    "example": 11998765432
                  },
                  "federalTaxId": {
                    "type": "string",
                    "description": "Número de identificação fiscal da pessoa destinatária associada ao pacote. Poder ser o número do CPF ou CNPJ.",
                    "example": 12345678911
                  },
                  "address": {
                    "oneOf": [
                      {
                        "type": "object",
                        "properties": {
                          "correios": {
                            "type": "object",
                            "properties": {
                              "logradouro": {
                                "type": "string",
                                "description": "Nome do endereço associado a pessoa destinatária do pacote.",
                                "example": "Alameda Santos"
                              },
                              "numero": {
                                "type": "string",
                                "description": "Número que identifica o local onde o pacote será entregue para a pessoa destinatária associada ao pacote.",
                                "example": 2400
                              },
                              "complemento": {
                                "type": "string",
                                "description": "Informações complementares associadas ao endereço da pessoa destinatária do pacote.",
                                "example": "Apto 103, Bloco C"
                              },
                              "bairro": {
                                "type": "string",
                                "description": "Bairro do endereço associado a pessoa destinatária do pacote.",
                                "example": "Centro"
                              },
                              "cep": {
                                "type": "string",
                                "description": "Código postal do endereço associado a pessoa destinatária do pacote.",
                                "example": 12345000
                              },
                              "cidade": {
                                "type": "string",
                                "description": "Cidade do endereço associado a pessoa destinatária do pacote.",
                                "example": "São Paulo"
                              },
                              "uf": {
                                "type": "string",
                                "description": "Unidade federativa do endereço associado a pessoa destinatária do pacote.",
                                "example": "SP"
                              }
                            }
                          }
                        },
                        "description": "Objeto que contém informações detalhadas do endereço compatível com o formato da API dos Correios."
                      },
                      {
                        "type": "object",
                        "properties": {
                          "lines": {
                            "type": "object",
                            "properties": {
                              "addressLine1": {
                                "type": "string",
                                "description": "Representação mais simples do endereço associado a pessoa destinatária do pacote. Comumente associado ao formato inserido pelo usuário.",
                                "example": "Alameda Santos, 2400"
                              },
                              "addressLine2": {
                                "type": "string",
                                "description": "Informações complementares associadas ao endereço da pessoa destinatária do pacote.",
                                "example": "Apto 103 - Bloco C"
                              },
                              "postalCode": {
                                "type": "string",
                                "description": "Código postal do endereço associado a pessoa destinatária do pacote. No Brasil, usa-se o CEP.",
                                "example": 12345000
                              },
                              "city": {
                                "type": "string",
                                "description": "Cidade do endereço associado a pessoa destinatária do pacote.",
                                "example": "São Paulo"
                              },
                              "state": {
                                "type": "string",
                                "description": "Unidade federativa do endereço associado a pessoa destinatária do pacote.",
                                "example": "SP"
                              },
                              "country": {
                                "type": "string",
                                "description": "País do endereço associado a pessoa destinatária do pacote.",
                                "example": "Brasil"
                              }
                            }
                          }
                        },
                        "description": "Objeto que representa um endereço com padrão internacional."
                      }
                    ],
                    "description": "Objeto que representa um endereço nacional em formato dos Correios ou um endereço internacional. Ambas as representações são mutuamente exclusivas, sendo assim, só é possível utilizar uma delas por request."
                  }
                },
                "description": "Objeto que configura o formato da requisição de atualização do destinatário. Contém as informações da pessoa destinatária e do endereço de entrega."
              }
            }
          }
        },
        "description": "Objeto que configura o formato da requisição de atualização de um pacote. Contém as informações a serem atualizadas."
      },
      "v1PackageCancelResponse": {
        "type": "object",
        "properties": {
          "warning_type": {
            "type": "string",
            "description": "Mensagem com a constante que identifica casos em que o cancelamento não pode ser confirmado.",
            "example": "REDISPATCH_CANCELLATION"
          },
          "warning_message": {
            "type": "string",
            "description": "Mensagem de alerta para casos em que o cancelamento não pode ser confirmado.",
            "example": "O pacote está com os correios. Vamos tentar cancelar e devolver pra você."
          }
        },
        "description": "Objeto que configura a resposta da API de cancelamento de pacotes."
      },
      "ErrorMessage": {
        "type": "object",
        "properties": {
          "code": {
            "type": "integer",
            "format": "int32",
            "description": "Código numérico referente à falha.\nINVALID_ARGUMENT = 3\nNOT_FOUND = 5\nPERMISSION_DENIED = 7\nRESOURCE_EXHAUSTED = 8\nFAILED_PRECONDITION = 9\nINTERNAL = 13\nUNAVAILABLE = 14\nUNAUTHENTICATED = 16",
            "example": 14
          },
          "message": {
            "type": "string",
            "description": "Texto pequeno informativo sobre a falha.",
            "example": "Requisição com credenciais inválidas."
          },
          "details": {
            "type": "array",
            "description": "Detalhes sobre a falha. Nesta versão da API ainda não está sendo retornado, mas deve ser considerado um array de objetos de tipos distintos.",
            "items": {},
            "example": []
          }
        }
      }
    }
  }
}